# Generated by Django 3.2.18 on 2023-04-12 23:19

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='default_picture',
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calendar_default_picture',
                to=settings.FILER_IMAGE_MODEL,
                verbose_name='default picture'
            ),
        ),
    ]
