# Generated by Django 4.2.5 on 2023-09-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_events', '0002_calendar_default_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='classification',
            field=models.CharField(
                blank=True,
                default='',
                max_length=64,
                verbose_name='classification'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(
                blank=True, default='', max_length=64, verbose_name='duration'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='location'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='organizer'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(
                blank=True, default='', max_length=64, verbose_name='status'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='uid'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlistplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin'
            ),
        ),
    ]
